button_card_templates: !include_dir_merge_named custom_dashboards/button_card_templates
decluttering_templates: !include_dir_merge_named custom_dashboards/decluttering_templates

views: !include_dir_list custom_dashboards/views/default