id: casa_atualiza_detectores_de_problemas
alias: "Casa: Atualiza Detectores de Problemas"
description: ""
mode: single
trigger:
    - alias: "o relógio entrar no minuto 24"
      platform: time_pattern
      minutes: "24"
action:
    - alias: "Chama o script de Atualização dos Detectores de Problemas"
      service: script.turn_on
      target:
          entity_id: script.casa_atualiza_detectores_de_problemas
