id: casa_cameras_atualiza_destaque_atual
alias: "Casa: Câmeras: Atualiza Destaque Atual"
description: "Automação que atualiza a 'Câmera em Destaque' quando o evento ao iniciar o Home Assistant ou recarregar as entidade da integração 'Template'"
mode: single
trigger:
    - alias: "As entidades da plataforma template são recarregadas"
      platform: event
      event_type: event_template_reloaded
    - alias: "O Home Assistant é ligado."
      platform: homeassistant
      event: start
action:
    - alias: "Chama o script 'Casa: Câmeras: Atualiza Destaque Atual'"
      service: script.turn_on
      target:
          entity_id: script.casa_cameras_atualiza_destaque_atual
      data:
          variables:
              camera_name: "Frente: Câmera da Garagem"
