id: casa_detector_de_problemas_atualiza_problemas_com_entidades
alias: "Casa: Detector de Problemas: Atualiza Problemas com Entidades"
description: ""
mode: single
trigger:
    - alias: "o relógio entrar no minuto 24"
      platform: time_pattern
      minutes: "24"
action:
    - alias: "Chama o script 'Casa: Detector de Problemas: Atualiza Problemas com Entidades"
      service: script.turn_on
      target:
          entity_id: script.casa_detector_de_problemas_atualiza_problemas_com_entidades
