id: "casa_notificar_atividades"
alias: "Casa: Notificar Atividades"
description: ""
mode: queued
max: 10
trigger:
    - id: casa_notificar_atividades_selected_devices_state_trigger
      alias: "Dispositivos selecionados mudam de estado."
      platform: state
      entity_id:
          - cover.frente_portao_da_garagem
          - climate.quarto_do_edu_ar_condicionado
          - light.quarto_do_edu_luz_de_teto
          - light.quarto_do_edu_luz_de_cabeceira
          - light.fundos_fita_de_led
          - light.escritorio_luz_de_teto
      from: null
      to: null
    # - id: casa_notificar_atividades_frente_portao_da_garagem_state_trigger
    #   platform: state
    #   entity_id:
    #       - cover.frente_portao_da_garagem
    #   from:
    #   to:
    - id: casa_notificar_atividades_hass_start_trigger
      alias: "O Home Assistant é ligado."
      platform: homeassistant
      event: start
    - id: casa_notificar_atividades_hass_shutdown_trigger
      alias: "O Home Assistant é desligado."
      platform: homeassistant
      event: shutdown
condition: []
action:
    - alias: "uma das opções"
      choose:
          - alias: "Notificar Telegram, quando dispositivos selecionados mudam de estado"
            conditions:
                - alias: "Quando dispositivos selecionados mudam de estado."
                  condition: trigger
                  id:
                      - casa_notificar_atividades_selected_devices_state_trigger
            sequence:
                - alias: "Enviar notificação com as modificações via Telegram"
                  service: telegram_bot.send_message
                  data:
                      title: "{{ trigger.from_state.name }}"
                      message: |
                          {% from 'translator.jinja' import format_state %}
                          {{ format_state(trigger.from_state) }}
                          {{- ' ➡️ ' }}
                          {{- format_state(trigger.to_state) }}
          - alias: "Notificar Telegram, quando o Home Assistant é desligado"
            conditions:
                - alias: "Quando o Home Assistant for desligado:"
                  condition: trigger
                  id:
                      - casa_notificar_atividades_hass_off_trigger
            sequence:
                - alias: "Enviar notificação via Telegram"
                  service: telegram_bot.send_message
                  data:
                      title: "{{ 'Home Assistant' }}"
                      message: |
                          {{ 'Ligado' }} ➡️ {{ 'Desligado' }}
          - alias: "Notificar Telegram, quando o Home Assistant é ligado"
            conditions:
                - alias: "Quando o Home Assistant for ligado:"
                  condition: trigger
                  id:
                      - casa_notificar_atividades_hass_on_trigger
            sequence:
                - alias: "Enviar notificação via Telegram"
                  service: telegram_bot.send_message
                  data:
                      title: "{{ 'Home Assistant' }}"
                      message: |
                          {{ 'Desligado' }} ➡️ {{ 'Ligado' }}
          # - conditions:u
          #       - condition: trigger
          #         id:
          #             - casa_notificar_atividades_frente_portao_da_garagem_state_trigger
          #   sequence:
          #       - service: camera.record
          #         target:
          #             entity_id: camera.frente_camera_da_lateral
          #         data:
          #             duration: 10
          #             filename: /config/www/records/frente_camera_da_garagem.mp4
          #       - service: telegram_bot.send_video
          #         data:
          #             file: /config/www/records/frente_camera_da_garagem.mp4
