resource: "http://192.168.15.150:1984/api/streams?src=fundos_camera_do_quintal"
sensor:
  - unique_id: "frontend_cameras_camera_do_quintal_conexoes"
    name: "Frontend: Câmeras: Câmera do Quintal: Conexões"
    availability: '{{ is_state("binary_sensor.servicos_supervisor_go2rtc_executando", "on") }}'
    value_template: >
        {% if value_json is defined and 'consumers' in value_json and value_json.consumers is not none %}
          {{ value_json.consumers | count }}
        {% else %}
          {{ 0 }}
        {% endif %}
    state_class: measurement
binary_sensor:
  - unique_id: "frontend_cameras_camera_do_quintal_status"
    name: "Frontend: Câmeras: Câmera do Quintal: Status"
    availability: '{{ is_state("binary_sensor.servicos_supervisor_go2rtc_executando", "on") }}'
    value_template: >
      {% if value_json %}
        {{ (value_json.producers | count) > 0 }}
      {% else %}
        {{ False }}
      {% endif %}
    device_class: connectivity